#####   BASIC   ######################################
debug: true
use_wandb: false
wandb_project: kaggle_mga_keypoints_detection
dataset_name: data0002
seed: 77
n_epochs: 5
split_method: StratifiedKFold
n_folds: 5
use_fold: [0] # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
save_model: true
use_amp: true

#####   Pretrained   ###################################
restart: false
pretrained_model_from_net_path: naver-clova-ix/donut-base
pretrained_model_path:

##### Optimizer ########################################
optimizer: AdamW
lr: 3e-5
weight_decay: 1e-6

##### Image Info ########################################
# img_mean: [0.485, 0.456, 0.406]
# img_std: [0.229, 0.224, 0.225]
img_h: 560
img_w: 560

##### Text Info #########################################
max_length: 1024

##### DataLoader ########################################
train_bs: 4
valid_bs: 4
num_workers: 2
