#####   BASIC   ########################################
use_wandb: false
wandb_project: kaggle_mga_chart_classification
dataset_name: data0001
seed: 77
epoch: 10
split_method: StratifiedKFold
n_folds: 5
use_fold: [0] # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
save_model: true
from_lmdb: true

######   Model   #######################################
model_arch: centernet
pretrained: true
input_channel: 3
output_channel: 1

######   Loss   ########################################
loss: CrossEntropyLoss # MSELoss, BCEWithLogitsLoss, RMSELoss, FOCALLoss
gamma: 0. # FOCALLoss

##### Optimizer ########################################
optimizer: AdamW
lr: 1e-3
weight_decay: 1e-6

##### Scheduler ########################################
scheduler: OneCycleLR # OneCycleLR
T_0: ${epoch} # CAWR
T_mult: 1 # CAWR
eta_min: 1e-9 # CAWR

pct_start: 0.1 # OCLR
div_factor: 25. # OCLR
final_div_factor: 1000. # OCLR

##### Image Info ########################################
img_mean: [0.485, 0.456, 0.406]
img_std: [0.229, 0.224, 0.225]
img_size: 384

##### DataLoader ########################################
train_bs: 32
valid_bs: 32
num_workers: 2

##### MixUp #############################################
mix_p: 0.
init_nomix_epoch: 0
last_nomix_epoch: 0

##### Data Augmentation #################################
train_aug:
  RandomResizedCrop:
    height: ${img_size}
    width: ${img_size}
    p: 1.0
  Normalize:
    mean: ${img_mean}
    std: ${img_std}
    max_pixel_value: 255.0
    p: 1.0

valid_aug:
  Resize:
    height: ${img_size}
    width: ${img_size}
  Normalize:
    mean: ${img_mean}
    std: ${img_std}
    max_pixel_value: 255.0
    p: 1.0

tta_aug:
  Normalize:
    mean: ${img_mean}
    std: ${img_std}
    max_pixel_value: 255.0
    p: 1.0
  Resize:
    height: ${img_size}
    width: ${img_size}
  RandomResizedCrop:
    height: ${img_size}
    width: ${img_size}
    scale: [0.3, 1.0]
    p: 1.0
  HorizontalFlip: 
    p: 0.5
  VerticalFlip: 
    p: 0.5