#####   BASIC   ######################################
debug: true
use_wandb: false
wandb_project: kaggle_mga_image2text
dataset_name: data0002
seed: 77
n_epochs: 3
split_method: StratifiedKFold
n_folds: 5
use_fold: [0] # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
save_model: true
use_amp: true
n_valid_per_epoch: 10

#####   Pretrained   ###################################
restart: false
pretrained_model_from_net_path: google/matcha-chart2text-statista
pretrained_model_path:

##### Optimizer ########################################
optimizer: AdamW
lr: 1e-2
weight_decay: 1e-5

##### Scheduler ########################################
scheduler: OneCycleLR # OneCycleLR
scheduler_step_time: step
T_0: ${n_epochs} # CAWR
T_mult: 1 # CAWR
eta_min: 1e-9 # CAWR

pct_start: 0.1 # OCLR
div_factor: 100. # OCLR
final_div_factor: 1000. # OCLR

##### Image Info ########################################
# img_mean: [0.485, 0.456, 0.406]
# img_std: [0.229, 0.224, 0.225]
img_h: 560
img_w: 560

##### Text Info #########################################
max_length: 1024
max_patches: 1024

##### DataLoader ########################################
train_bs: 2
valid_bs: 2
num_workers: 2
